app:
  path: /
  controller: App\Controller\IndexController

legals:
  path: /legals
  controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
  defaults:
    template: legals.html.twig
